version: '3'

services:
  postgres:
    image: postgres
    container_name: diary-postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - diary-network
  
  diary-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diary-api
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/diary/
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - diary-network
      
volumes:
  postgres-db:

networks:
  diary-network: